apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  - name: http
    port: 80
    targetPort: web
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  sessionAffinity: ClientIP
  type: ClusterIP
# ---
# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: prometheus-cert
#   namespace: monitoring
# spec:
#   domains:
#     - prometheus.leosete-sre-devops.com
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     ingressclass.kubernetes.io/is-default-class: "true"
#     kubernetes.io/ingress.class: gce
#     kubernetes.io/ingress.global-static-ip-name: gke-lb-ext-leosete-monitoring
#     networking.gke.io/managed-certificates: prometheus-cert
#   labels:
#     app.kubernetes.io/component: prometheus
#     app.kubernetes.io/instance: k8s
#     app.kubernetes.io/name: prometheus
#     app.kubernetes.io/part-of: kube-prometheus
#     app.kubernetes.io/version: 2.47.0
#   name: prometheus-ext
#   namespace: monitoring
# spec:
#   rules:
#   - host: prometheus.leosete-sre-devops.com
#     http:
#       paths:
#       - backend:
#           service:
#             name: prometheus-k8s
#             port:
#               number: 80
#         path: /
#         pathType: Prefix
